main: su.nightexpress.divineitems.DivineItems
version: 3.9.5-Beta-Pre4
name: DivineItemsRPG
author: NightExpress
desciption: An advanced, powerful item plugin like in MMORPG games with stats, gems, item sets, scrolls, potions and more more more!
softdepend:
- BattleLevels
- Citizens
- DivineClassesRPG
- Heroes
- HolographicDisplays
- mcMMO
- MythicMobs
- PlaceholderAPI
- RacesOfThana
- RPGInventory
- RPGme
- SkillAPI
- Skills
- Vault
- WorldGuard
commands:
  divineitems:
    aliases: [di, ditems]
    description: Base command.
permissions:
   divineitems.user:
      description: User access
      default: true
   divineitems.resolve:
      description: Resolve items
      default: true
   divineitems.repair.anvil:
      description: Repair items on anvil
      default: true
   divineitems.bypass.owner:
      description: Allows to use someones item
      default: op
   divineitems.bypass.soulbound:
      description: Allows to use item without soulbound
      default: op
   divineitems.bypass.level:
      description: Allows to bypass the item level
      default: op
   divineitems.bypass.class:
      description: Allows to bypass the item class
      default: op
   divineitems.admin:
      description: Full access
      default: op