#+------------------------------------------------------------+
#|               Divine Items RPG 3.0 Beta                    |
#|                Created by NightExpress                     |
#|                Thanks for the purchase!                    |
#|   If you really like this plugin, please leave a review!   |
#|      Let me know if you have any problems/questions        |
#+------------------------------------------------------------+
Lang: en

Global:
  LevelPlugin: NONE
  ClassPlugin: NONE
  DamageFormula:
    other: '(1 + (%pvpe_dmg% - %pvpe_def%) / 100) * (1 - %block% / 100)'
    damage: '(%dmg% * %other%)'
  DamageReduceCooldown: 0.0
  BreakItems: true
  MaxGetTargetDistance: 30
  AttributeFormat: '%att_prefix% %att_name%: %att_value%'
  DamageTypeFormat: '%type_prefix% %type_name%: %type_value%'
  ArmorTypeFormat: '%type_prefix% %type_name%: %type_value%'
  AmmoTypeFormat: '&7Ammo Type: %type_prefix% %type_name%'
  AllowAttributesToMobs: true
  AllowFishHookDamage: true
  AllowAttributesInOffHand: false
  SkillAPISkillsReduceDurability: true

Modules:
  Abilities: true
  Abyss Dust: true
  Buffs: true
  Combat Log: true
  Custom Items: true
  Drops: true
  Enchants: true
  Gems: true
  Identify: true
  Item Hints: true
  Magic Dust: true
  Notifications: true
  Repair: true
  Resolve: true
  Runes: true
  Scrolls: true
  Soulbound: true
  Tiers: true
  Sets: true

Strings:
  DamageSeparator: ' &7- '
  DurabilitySeparator: '&7/'
  Percent: '%'
  Negative: '&c'
  Positive: '&a+'
  Modifier: 'x'
  Level: '&cRequires %n level to use.'
  Class: '&cOnly for: '
  ClassSeparator: '&7/'
  ClassColor: '&f'

DamageModifiers:
  ENTITY_ATTACK:
    PLAYER: 1.0
    MOB: 1.0
  FIRE:
    PLAYER: 1.0
    MOB: 1.0
  POISON:
    PLAYER: 2.15
    MOB: 2.0

DamageTypes:
  Physical:
    Default: true
    Prefix: '&6⚔'
    Name: 'Physical Damage'
    Value: '&f'
    HitActions: []
    BiomeDamageModifier:
      PLAINS: 1.0
  Magical:
    Prefix: '&d⚡'
    Name: 'Magical Damage'
    Value: '&f'
    HitActions:
    - '[EFFECT] CRIT_MAGIC 0.5 0.5 0.5 0.05 50 @Target'
    BiomeDamageModifier:
      PLAINS: 1.0
  Fire:
    Default: false
    Prefix: '&c☀'
    Name: 'Fire Damage'
    Value: '&f'
    HitActions:
    - '[EFFECT] FLAME 0.5 0.5 0.5 0.05 50 @Target'
    BiomeDamageModifier:
      PLAINS: 1.0
      NETHER: 1.25
  Poison:
    Default: false
    Prefix: '&a☣'
    Name: 'Poison Damage'
    Value: '&f'
    HitActions:
    - '[EFFECT] SLIME 0.5 0.5 0.5 0.05 50 @Target'
    BiomeDamageModifier:
      PLAINS: 1.0
      SWAMPLAND: 1.25
  Water:
    Default: false
    Prefix: '&9⚓'
    Name: 'Water Damage'
    Value: '&f'
    HitActions:
    - '[EFFECT] DRIP_WATER 0.5 0.5 0.5 0.05 50 @Target'
    BiomeDamageModifier:
      PLAINS: 1.0
      OCEAN: 1.25
  Wind:
    Default: false
    Prefix: '&7⚕'
    Name: 'Wind Damage'
    Value: '&f'
    HitActions:
    - '[EFFECT] SMOKE_NORMAL 0.5 0.5 0.5 0.05 50 @Target'
    BiomeDamageModifier:
      PLAINS: 1.0

ArmorTypes:
  Physical:
    Prefix: '&6▸'
    Name: 'Physical Defense'
    Value: '&f'
    Percent: false # Add + and %
    BlockDamageSource:
    - ENTITY_ATTACK
    BlockDamageTypes:
    - Physical
    Formula: '((%dmg% * (1 + %penetrate% / 100)) - (%def% / 10))'
  Magical:
    Prefix: '&d▸'
    Name: 'Magical Defense'
    Value: '&f'
    Percent: false # Add + and %
    BlockDamageSource:
    - ENTITY_ATTACK
    BlockDamageTypes:
    - Magical
    Formula: '((%dmg% * (1 + %penetrate% / 100)) - (%def% / 10))'
  Fire:
    Prefix: '&c▸'
    Name: 'Fire Defense'
    Value: '&f'
    Percent: false # Add + and %
    BlockDamageSource:
    - ENTITY_ATTACK
    BlockDamageTypes:
    - Fire
    Formula: '((%dmg% * (1 + %penetrate% / 100)) - (%def% / 10))'
  Poison:
    Prefix: '&a▸'
    Name: 'Poison Defense'
    Value: '&f'
    Percent: false # Add + and %
    BlockDamageSource:
    - ENTITY_ATTACK
    BlockDamageTypes:
    - Poison
    Formula: '((%dmg% * (1 + %penetrate% / 100)) - (%def% / 10))'
  Water:
    Prefix: '&9▸'
    Name: 'Water Defense'
    Value: '&f'
    Percent: false # Add + and %
    BlockDamageSource:
    - ENTITY_ATTACK
    BlockDamageTypes:
    - Water
    Formula: '((%dmg% * (1 + %penetrate% / 100)) - (%def% / 10))'
  Wind:
    Prefix: '&7▸'
    Name: 'Wind Defense'
    Value: '&f'
    Percent: false # Add + and %
    BlockDamageSource:
    - ENTITY_ATTACK
    BlockDamageTypes:
    - Wind
    Formula: '((%dmg% * (1 + %penetrate% / 100)) - (%def% / 10))'


AmmoTypes:
  ARROW:
    Enabled: true
    Prefix: '&f➶'
    Name: 'Arrow'
  SNOWBALL:
    Enabled: true
    Prefix: '&9❄&f'
    Name: 'Snowball'
  EGG:
    Enabled: true
    Prefix: '&6⚫&f'
    Name: 'Egg'
  FIREBALL:
    Enabled: true
    Prefix: '&c☄&f'
    Name: 'Fireball'
  WITHER_SKULL:
    Enabled: true
    Prefix: '&8☢&f'
    Name: 'Wither Skull'
  SHULKER_BULLET:
    Enabled: true
    Prefix: '&d✦&f'
    Name: 'Shulker Bullet'
  LLAMA_SPIT:
    Enabled: true
    Prefix: '&e☔&f'
    Name: 'Llama Spit'
  ENDER_PEARL:
    Enabled: true
    Prefix: '&b◉&f'
    Name: 'Ender Pearl'
  EXP_POTION:
    Enabled: true
    Prefix: '&e☘&f'
    Name: 'Exp Potion'

AttributeSettings:
  BLEED_RATE:
    Time: 5
    Formula: '%dmg% * 0.25'
    Effect: 'REDSTONE:RED'
  DISARM_RATE:
    Effect: 'CRIT'
    Message:
      Damager: '&2*** &aYou disarmed &7%s%&a! &2***'
      Entity: '&4*** &cYou have been disarmed by &7%s%&c! &4***'

Attributes:
  DIRECT_DAMAGE:
    Name: Direct Damage
    Prefix: '&f▸'
    Value: '&f'
    Bonus: '&6⏏&f'
    Capability: 100.0
  AOE_DAMAGE:
    Name: AoE Damage
    Prefix: '&3▸'
    Value: '&f'
    Bonus: '&6⏏&f'
    Capability: -1
  PVP_DAMAGE:
    Name: 'PvP Damage'
    Prefix: '&b▸'
    Value: '&f'
    Bonus: '&6⏏&f'
    Capability: 200.0
  PVE_DAMAGE:
    Name: 'PvE Damage'
    Prefix: '&b▸'
    Value: '&f'
    Bonus: '&6⏏&f'
    Capability: 200.0
  DODGE_RATE:
    Name: 'Dodge Rate'
    Prefix: '&6▸'
    Value: '&f'
    Bonus: '&6⏏&f'
    Capability: 45.0
  ACCURACY_RATE:
    Name: 'Accuracy Rate'
    Prefix: '&6▸'
    Value: '&f'
    Bonus: '&6⏏&f'
    Capability: 30.0
  BLOCK_RATE:
    Name: 'Block Rate'
    Prefix: '&6▸'
    Value: '&f'
    Bonus: '&6⏏&f'
    Capability: 55.0
  BLOCK_DAMAGE:
    Name: 'Block Damage'
    Prefix: '&6▸'
    Value: '&f'
    Bonus: '&6⏏&f'
    Capability: 75.0
  CRITICAL_RATE:
    Name: 'Crit. Strike Rate'
    Prefix: '&a▸'
    Value: '&f'
    Bonus: '&6⏏&f'
    Capability: 100.0
  CRITICAL_DAMAGE:
    Name: 'Crit. Strike Dmg'
    Prefix: '&a▸'
    Value: '&f'
    Bonus: '&6⏏&f'
    Capability: 3.5
  PVP_DEFENSE:
    Name: 'PvP Defense'
    Prefix: '&b▸'
    Value: '&f'
    Bonus: '&6⏏&f'
    Capability: 100.0
  PVE_DEFENSE:
    Name: 'PvE Defense'
    Prefix: '&b▸'
    Value: '&f'
    Bonus: '&6⏏&f'
    Capability: 100.0
  LOOT_RATE:
    Name: 'Loot Rate'
    Prefix: '&e▸'
    Value: '&f'
    Bonus: '&6⏏&f'
    Capability: 250.0
  MOVEMENT_SPEED:
    Name: 'Movement Speed'
    Prefix: '&e▸'
    Value: '&f'
    Bonus: '&6⏏&f'
    Capability: 70.0
  DURABILITY:
    Name: 'Durability'
    Prefix: '&a▸'
    Value: '&f'
    Bonus: '&6⏏&f'
    Capability: -1
  DURABILITY_UNBREAK:
    Name: 'Durability'
    Prefix: '&a▸'
    Value: '&f&lUnbreakable'
    Bonus: '&6⏏&f'
    Capability: -1
  PENETRATION:
    Name: 'Armor Penetration'
    Prefix: '&c▸'
    Value: '&f'
    Bonus: '&6⏏&f'
    Capability: 60.0
  VAMPIRISM:
    Name: 'Vampirism'
    Prefix: '&c▸'
    Value: '&f'
    Bonus: '&6⏏&f'
    Capability: 35.0
  BURN_RATE:
    Name: 'Chance to Burn'
    Prefix: '&c▸'
    Value: '&f'
    Bonus: '&6⏏&f'
    Capability: 100.0
  ATTACK_SPEED:
    Name: 'Attack Speed'
    Prefix: '&e▸'
    Value: '&f'
    Bonus: '&6⏏&f'
    Capability: -1
  MAX_HEALTH:
    Name: 'Max Health'
    Prefix: '&c▸'
    Value: '&f'
    Bonus: '&6⏏&f'
    Capability: 20

ItemGroups:
  Weapons:
  - WOOD_SWORD
  - WOOD_AXE
  - STONE_SWORD
  - STONE_AXE
  - GOLD_SWORD
  - GOLD_AXE
  - IRON_SWORD
  - IRON_AXE
  - DIAMOND_SWORD
  - DIAMOND_AXE
  - SHEARS
  - FISHING_ROD
  - BOW
  Tools:
  - WOOD_HOE
  - WOOD_AXE
  - WOOD_SPADE
  - WOOD_PICKAXE
  - STONE_HOE
  - STONE_AXE
  - STONE_SPADE
  - STONE_PICKAXE
  - GOLD_HOE
  - GOLD_AXE
  - GOLD_SPADE
  - GOLD_PICKAXE
  - IRON_HOE
  - IRON_AXE
  - IRON_SPADE
  - IRON_PICKAXE
  - DIAMOND_HOE
  - DIAMOND_AXE
  - DIAMOND_SPADE
  - DIAMOND_PICKAXE
  - SHEARS
  - FISHING_ROD
  Armors:
  - LEATHER_HELMET
  - LEATHER_CHESTPLATE
  - LEATHER_LEGGINGS
  - LEATHER_BOOTS
  - GOLD_HELMET
  - GOLD_CHESTPLATE
  - GOLD_LEGGINGS
  - GOLD_BOOTS
  - CHAINMAIL_HELMET
  - CHAINMAIL_CHESTPLATE
  - CHAINMAIL_LEGGINGS
  - CHAINMAIL_BOOTS
  - IRON_HELMET
  - IRON_CHESTPLATE
  - IRON_LEGGINGS
  - IRON_BOOTS
  - DIAMOND_HELMET
  - DIAMOND_CHESTPLATE
  - DIAMOND_LEGGINGS
  - DIAMOND_BOOTS
  - SHIELD
  - ELYTRA

cfg_version: 3.0.0