name: Secure Unzip
on: [push]

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # 显式声明令牌

    - name: Unzip files
      run: unzip -O GBK *.zip -d extracted/cydl

    - name: Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "安全解压"
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
