name: Secure Unzip
on: [push]

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4  # 升级到v4
      
    - name: Install 7z
      run: sudo apt-get install p7zip-full -y

    - name: Check ZIP existence
      run: test -f su.zip || (echo "Error: su.zip未找到"; exit 1)

    - name: Unzip files
      run: 7z x -oextracted/cydl su.zip  # 更兼容的压缩工具

    - name: Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "安全解压"
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        skip_empty_commit: true
