name: Unzip Folder
on: [push]
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: unzip your.zip -d target_folder/
    - uses: stefanzweifel/git-auto-commit-action@v4
